### ISSUE TITLE
Bspswallow breaks bspc node switching

### ISSUE THREAD

**Issue by proskehy** [JopStro/bspswallow#13]
Steps to reproduce:

1. Bind `bspc node -f next.local.window` to a shortcut of your choosing
2. Disable `bspswallow`
3. Open a couple of windows
4. Try running the shortcut, see that it correctly switches between windows on current desktop 
5. Enable bspswallow
6. Open a couple of windows, including a swallowed window (e.g. mpv started from a terminal)
7. Try running the shortcut, see that bspc isn't able to "return" to the swallowed window.

**Comment by JopStro** [comment]
Sorry I took so long to see this, but your problem seems to just be a quirk of how windows are swallowed, as when that command is run bspwm is trying to select the window which is hidden through swallowing, which it of course can't, so nothing happens. Flagging the swallowed window as hidden is the only way of making swallowing work so this won't be fixable afaik. There may be a way to make an equivilent command that ignores hidden windows, if not you could suggest it as a feature for bspwm itself.
