### ISSUE TITLE
Libreoffice breaks alot of swallowing 

### ISSUE THREAD

**Issue by Jack-O-Brian** [JopStro/bspswallow#3]
Due to how LibreOffice spawns another window, it breaks a lot of compatibility. here's the edge cases I found so far. One thing that's bugging me is it works unexpectedly, and I can't pinpoint why.

- 1 Terminal: Sometimes it works, some times it doesn't.  
Output: `URxvt
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  21 (X_ListProperties)
  Resource id in failed request:  0x3600001
  Serial number of failed request:  12
  Current serial number in output stream:  12
0x03600001 0x0120040B`
- 2 Terminal: the other terminal gets swallowed. If I try to open the same file with the other terminal, it does not work.

If need be I can supply video of this. I think all in all LibreOffice cannot be swallowed.

**Comment by JopStro** [comment]
Just tested it out, and it seems pretty bad. Not sure how the first one happened but the second one was most likley due to a terminal being focused when the splash is up (from hover to focus). I'll leave the issue open in case anyone wants to give a wack at a solution, but it doesn't really seem worth the effort right now. Will update the README to mention this.

**Comment by JopStro** [comment]
Just did some experementing and the problem can be somewhat avoided by using the --no-logo option (removing the splash screen). I also reccomend turning off tip of the day because it seems to usually appear before the main window.
