### ISSUE TITLE
Swallow everything spawned with the terminal on focus

### ISSUE THREAD

**Issue by tarwinmuralli** [JopStro/bspswallow#9]
Swallow everything spawned with the terminal on focus
Steps to reproduce:
1. Open terminal (i am using st)
2. spawn anything using sxhd (example : pcmanfm)
3. pcmanfm gets swallowed by the terminal

if the terminal is not focused it works fine
or is it part of the feature

**Comment by JopStro** [comment]
Not entirely sure what your issue is, but if you are refering to programs that do not originate from the terminal (such as from dmenu) then this is a known byproduct of how the script works. It can be circumvented by temporaraly disabling the script while spawning the window (an example using dmenu_run exists in the examples directory)

**Comment by ghost** [comment]
You can create a script in your path that looks something like this:

File: sxhkd_noswallow
```
#!/bin/sh
killall bspswallow
eval "$1" >/dev/null
sleep 2
bspswallow &
```
And then you call your programs in your sxhkdrc like this:
```
ctrl + alt + f
       sxhkd_noswallow firefox
```

**Comment by tarwinmuralli** [comment]
Thank you very much iosevka-soz. JopStro should probably add this this script inside the script folder
